// Raaha Boutique - Product Catalogue Data
const PRODUCTS = [
  // ===== WOMEN'S SAREES =====
  { id:1, name:"Royal Banarasi Silk Saree", category:"sarees", gender:"women", price:18999, originalPrice:24999, description:"Exquisite handwoven Banarasi silk saree with intricate zari work and traditional motifs. Perfect for weddings.", sizes:["Free Size"], colors:["Red & Gold","Navy & Silver","Maroon & Gold"], stock:"in-stock", badge:"Bestseller", gradient:["#8B1A1A","#DAA520"], fabric:"Pure Banarasi Silk", occasion:"Wedding" },
  { id:2, name:"Kanjeevaram Temple Border Saree", category:"sarees", gender:"women", price:24500, originalPrice:null, description:"Authentic Kanjeevaram silk with temple border design, handcrafted by master weavers of Tamil Nadu.", sizes:["Free Size"], colors:["Deep Green & Gold","Purple & Gold"], stock:"in-stock", badge:"", gradient:["#1B4332","#DAA520"], fabric:"Kanjeevaram Silk", occasion:"Wedding" },
  { id:3, name:"Chiffon Sequin Work Saree", category:"sarees", gender:"women", price:8999, originalPrice:12999, description:"Lightweight chiffon saree with delicate sequin embellishments, ideal for evening celebrations.", sizes:["Free Size"], colors:["Dusty Pink","Mint Green","Lavender"], stock:"in-stock", badge:"Sale", gradient:["#D4A5A5","#E8D5D5"], fabric:"Pure Chiffon", occasion:"Party" },
  { id:4, name:"Georgette Floral Print Saree", category:"sarees", gender:"women", price:6499, originalPrice:null, description:"Elegant georgette saree with contemporary floral prints and contrast border.", sizes:["Free Size"], colors:["Teal","Coral","Ivory"], stock:"low-stock", badge:"", gradient:["#2D6A6A","#4ECDC4"], fabric:"Georgette", occasion:"Casual" },
  { id:5, name:"Mysore Silk Classic Saree", category:"sarees", gender:"women", price:12999, originalPrice:null, description:"Luxurious Mysore silk saree featuring a rich pallu and pure gold kasab border.", sizes:["Free Size"], colors:["Royal Blue","Wine Red"], stock:"in-stock", badge:"", gradient:["#1B1464","#4A148C"], fabric:"Mysore Silk", occasion:"Festive" },
  { id:6, name:"Net Embroidered Party Saree", category:"sarees", gender:"women", price:9750, originalPrice:13500, description:"Stunning net saree with thread and pearl embroidery. A showstopper at any celebration.", sizes:["Free Size"], colors:["Black & Gold","Champagne"], stock:"in-stock", badge:"New", gradient:["#1C1C1C","#C9A96E"], fabric:"Net", occasion:"Party" },
  { id:7, name:"Tussar Silk Handloom Saree", category:"sarees", gender:"women", price:15800, originalPrice:null, description:"Authentic handloom Tussar silk with natural texture and hand-painted tribal motifs.", sizes:["Free Size"], colors:["Natural Gold","Rust"], stock:"in-stock", badge:"", gradient:["#B8860B","#D2691E"], fabric:"Tussar Silk", occasion:"Festive" },
  { id:8, name:"Organza Pearl Work Saree", category:"sarees", gender:"women", price:11200, originalPrice:14999, description:"Sheer organza saree embellished with hand-sewn pearls and scalloped border.", sizes:["Free Size"], colors:["Powder Blue","Blush Pink","Sage Green"], stock:"low-stock", badge:"Trending", gradient:["#B0C4DE","#F0E6EF"], fabric:"Organza", occasion:"Party" },
  { id:9, name:"Patola Double Ikat Saree", category:"sarees", gender:"women", price:28000, originalPrice:null, description:"Heritage Patola saree with double ikat weaving technique from Gujarat. A collector's piece.", sizes:["Free Size"], colors:["Red & Green","Blue & Yellow"], stock:"in-stock", badge:"Limited", gradient:["#C62828","#2E7D32"], fabric:"Patola Silk", occasion:"Wedding" },
  { id:10, name:"Chanderi Cotton Silk Saree", category:"sarees", gender:"women", price:7500, originalPrice:9999, description:"Delicate Chanderi saree blending cotton and silk with golden buti work.", sizes:["Free Size"], colors:["Off-White & Gold","Peach & Gold"], stock:"in-stock", badge:"", gradient:["#FFF8E7","#C9A96E"], fabric:"Chanderi Silk", occasion:"Casual" },

  // ===== WOMEN'S LEHENGAS =====
  { id:11, name:"Bridal Velvet Lehenga Set", category:"lehengas", gender:"women", price:68000, originalPrice:null, description:"Regal velvet lehenga with heavy zardozi embroidery, paired with embellished dupatta and blouse.", sizes:["S","M","L","XL"], colors:["Deep Maroon","Royal Red"], stock:"in-stock", badge:"Bridal", gradient:["#800020","#DAA520"], fabric:"Velvet", occasion:"Wedding" },
  { id:12, name:"Pastel Floral Organza Lehenga", category:"lehengas", gender:"women", price:32500, originalPrice:null, description:"Dreamy organza lehenga with 3D floral appliqué and layered tulle underskirt.", sizes:["S","M","L","XL"], colors:["Pastel Pink","Mint","Lilac"], stock:"in-stock", badge:"New", gradient:["#FFB6C1","#E6E6FA"], fabric:"Organza", occasion:"Engagement" },
  { id:13, name:"Embroidered Net Lehenga", category:"lehengas", gender:"women", price:24999, originalPrice:32000, description:"Net lehenga with intricate thread and sequin embroidery in contemporary motifs.", sizes:["S","M","L","XL"], colors:["Champagne","Dusty Rose"], stock:"in-stock", badge:"Sale", gradient:["#C9A96E","#D4A5A5"], fabric:"Net", occasion:"Reception" },
  { id:14, name:"Mirror Work Lehenga Choli", category:"lehengas", gender:"women", price:19800, originalPrice:null, description:"Vibrant lehenga with traditional mirror work (aabhla) from Kutch artisans.", sizes:["S","M","L"], colors:["Teal & Gold","Navy & Silver"], stock:"low-stock", badge:"", gradient:["#008080","#DAA520"], fabric:"Raw Silk", occasion:"Festive" },
  { id:15, name:"Silk A-Line Lehenga", category:"lehengas", gender:"women", price:28500, originalPrice:null, description:"Elegant A-line silhouette in pure silk with minimalist gold foil border.", sizes:["S","M","L","XL","XXL"], colors:["Emerald","Sapphire","Ruby"], stock:"in-stock", badge:"", gradient:["#046307","#1B4332"], fabric:"Pure Silk", occasion:"Wedding" },
  { id:16, name:"Ruffled Georgette Lehenga", category:"lehengas", gender:"women", price:15999, originalPrice:21000, description:"Modern ruffled lehenga in georgette with cascading layers and shimmer dupatta.", sizes:["S","M","L"], colors:["Blush","Sage","Powder Blue"], stock:"in-stock", badge:"Trending", gradient:["#D4A5A5","#A8B5A0"], fabric:"Georgette", occasion:"Party" },
  { id:17, name:"Sequin Party Lehenga", category:"lehengas", gender:"women", price:22000, originalPrice:null, description:"Glamorous sequin-encrusted lehenga perfect for cocktail nights and receptions.", sizes:["S","M","L","XL"], colors:["Gold","Silver","Rose Gold"], stock:"out-of-stock", badge:"", gradient:["#FFD700","#C0C0C0"], fabric:"Net & Sequin", occasion:"Party" },
  { id:18, name:"Raw Silk Bridal Lehenga", category:"lehengas", gender:"women", price:75000, originalPrice:null, description:"Opulent raw silk bridal lehenga with hand-embroidered heritage motifs and real gold zari.", sizes:["S","M","L","XL"], colors:["Bridal Red","Bridal Maroon"], stock:"in-stock", badge:"Exclusive", gradient:["#B22222","#DAA520"], fabric:"Raw Silk", occasion:"Wedding" },

  // ===== WOMEN'S ANARKALIS =====
  { id:19, name:"Floor Length Silk Anarkali", category:"anarkalis", gender:"women", price:14500, originalPrice:null, description:"Flowing floor-length Anarkali in pure silk with delicate gota patti work.", sizes:["S","M","L","XL"], colors:["Midnight Blue","Forest Green","Wine"], stock:"in-stock", badge:"", gradient:["#191970","#1B4332"], fabric:"Pure Silk", occasion:"Festive" },
  { id:20, name:"Net Embroidered Anarkali", category:"anarkalis", gender:"women", price:11999, originalPrice:15500, description:"Ethereal net Anarkali with layered flair and stone-studded yoke embroidery.", sizes:["S","M","L","XL"], colors:["Peach","Sky Blue","Lilac"], stock:"in-stock", badge:"Sale", gradient:["#FFDAB9","#87CEEB"], fabric:"Net", occasion:"Party" },
  { id:21, name:"Georgette Flair Anarkali", category:"anarkalis", gender:"women", price:8750, originalPrice:null, description:"Contemporary georgette Anarkali with dramatic flair and printed dupatta.", sizes:["S","M","L","XL","XXL"], colors:["Coral","Mustard","Teal"], stock:"in-stock", badge:"", gradient:["#FF7F50","#E8B741"], fabric:"Georgette", occasion:"Casual" },
  { id:22, name:"Velvet Winter Anarkali", category:"anarkalis", gender:"women", price:16200, originalPrice:null, description:"Luxurious velvet Anarkali with fur-trimmed dupatta, perfect for winter celebrations.", sizes:["S","M","L"], colors:["Deep Plum","Bottle Green","Burgundy"], stock:"low-stock", badge:"Seasonal", gradient:["#4A0E4E","#1B4332"], fabric:"Velvet", occasion:"Festive" },
  { id:23, name:"Chanderi Printed Anarkali", category:"anarkalis", gender:"women", price:7999, originalPrice:10500, description:"Lightweight Chanderi Anarkali with block-printed floral patterns.", sizes:["S","M","L","XL"], colors:["Off-White","Aqua","Peach"], stock:"in-stock", badge:"", gradient:["#FFF8E7","#7FDBDA"], fabric:"Chanderi", occasion:"Casual" },

  // ===== WOMEN'S GOWNS =====
  { id:24, name:"Indo-Western Evening Gown", category:"gowns", gender:"women", price:18500, originalPrice:null, description:"Stunning Indo-Western gown with structured bodice and flowing cape detail.", sizes:["S","M","L","XL"], colors:["Midnight Black","Champagne Gold"], stock:"in-stock", badge:"New", gradient:["#1C1C1C","#C9A96E"], fabric:"Satin & Net", occasion:"Party" },
  { id:25, name:"Cocktail Sequin Gown", category:"gowns", gender:"women", price:22999, originalPrice:28000, description:"Show-stopping cocktail gown fully encrusted with sequins and beadwork.", sizes:["S","M","L"], colors:["Silver","Rose Gold","Emerald"], stock:"in-stock", badge:"Sale", gradient:["#C0C0C0","#B76E79"], fabric:"Sequin Net", occasion:"Party" },
  { id:26, name:"Draped Satin Gown", category:"gowns", gender:"women", price:16800, originalPrice:null, description:"Minimalist draped satin gown with one-shoulder detail and thigh-high slit.", sizes:["S","M","L","XL"], colors:["Ivory","Dusty Rose","Olive"], stock:"in-stock", badge:"Trending", gradient:["#FFFFF0","#D4A5A5"], fabric:"Italian Satin", occasion:"Party" },
  { id:27, name:"Embellished Net Gown", category:"gowns", gender:"women", price:21000, originalPrice:null, description:"Fairy-tale net gown with cascading embellishments and layered tulle skirt.", sizes:["S","M","L","XL"], colors:["Baby Pink","Ice Blue","Lavender"], stock:"out-of-stock", badge:"", gradient:["#FFB6C1","#ADD8E6"], fabric:"Net & Tulle", occasion:"Reception" },
  { id:28, name:"Cape Style Designer Gown", category:"gowns", gender:"women", price:19500, originalPrice:25000, description:"Dramatic cape-style gown with metallic threadwork and trail detail.", sizes:["S","M","L"], colors:["Black & Gold","Navy & Gold"], stock:"in-stock", badge:"", gradient:["#1C1C1C","#DAA520"], fabric:"Georgette", occasion:"Party" },

  // ===== WOMEN'S KURTA SETS =====
  { id:29, name:"Silk Straight Kurta Set", category:"kurta-sets", gender:"women", price:5999, originalPrice:null, description:"Elegant straight-cut silk kurta with palazzo pants and contrast dupatta.", sizes:["S","M","L","XL","XXL"], colors:["Mustard","Teal","Maroon"], stock:"in-stock", badge:"", gradient:["#E8B741","#008080"], fabric:"Art Silk", occasion:"Festive" },
  { id:30, name:"Cotton Printed Kurta Palazzo", category:"kurta-sets", gender:"women", price:4500, originalPrice:5999, description:"Breezy cotton kurta with contemporary prints and matching palazzo pants.", sizes:["S","M","L","XL","XXL"], colors:["Blue & White","Pink & White","Green & White"], stock:"in-stock", badge:"", gradient:["#4169E1","#FFFFFF"], fabric:"Cotton", occasion:"Casual" },
  { id:31, name:"Chanderi Kurta Dupatta Set", category:"kurta-sets", gender:"women", price:7200, originalPrice:null, description:"Refined Chanderi kurta set with tissue dupatta and delicate zari accents.", sizes:["S","M","L","XL"], colors:["Powder Pink","Sage","Ivory"], stock:"in-stock", badge:"New", gradient:["#FFB6C1","#A8B5A0"], fabric:"Chanderi", occasion:"Festive" },
  { id:32, name:"Embroidered Rayon Kurta", category:"kurta-sets", gender:"women", price:3999, originalPrice:null, description:"Comfortable rayon kurta with chikankari-inspired embroidery. Everyday elegance.", sizes:["S","M","L","XL","XXL"], colors:["White","Sky Blue","Peach"], stock:"in-stock", badge:"", gradient:["#FFFFFF","#87CEEB"], fabric:"Rayon", occasion:"Casual" },
  { id:33, name:"Festive Silk Kurta Set", category:"kurta-sets", gender:"women", price:8500, originalPrice:11000, description:"Rich silk kurta set with gold printed motifs, perfect for festive gatherings.", sizes:["S","M","L","XL"], colors:["Ruby Red","Royal Purple","Emerald"], stock:"low-stock", badge:"Festive", gradient:["#9B111E","#6A0DAD"], fabric:"Pure Silk", occasion:"Festive" },

  // ===== MEN'S SHERWANIS =====
  { id:34, name:"Royal Silk Wedding Sherwani", category:"sherwanis", gender:"men", price:45000, originalPrice:null, description:"Magnificent silk sherwani with intricate hand-embroidered motifs and velvet detailing.", sizes:["36","38","40","42","44"], colors:["Ivory & Gold","Champagne & Silver"], stock:"in-stock", badge:"Bestseller", gradient:["#FFFFF0","#DAA520"], fabric:"Pure Silk", occasion:"Wedding" },
  { id:35, name:"Velvet Embroidered Sherwani", category:"sherwanis", gender:"men", price:38500, originalPrice:null, description:"Regal velvet sherwani with heavy zardozi work and silk lining.", sizes:["36","38","40","42","44"], colors:["Deep Maroon","Midnight Blue"], stock:"in-stock", badge:"", gradient:["#800020","#191970"], fabric:"Velvet", occasion:"Wedding" },
  { id:36, name:"Jacquard Reception Sherwani", category:"sherwanis", gender:"men", price:28999, originalPrice:35000, description:"Self-textured jacquard sherwani with minimalist embroidery, perfect for receptions.", sizes:["36","38","40","42","44"], colors:["Beige","Light Grey","Powder Blue"], stock:"in-stock", badge:"Sale", gradient:["#F5F5DC","#D3D3D3"], fabric:"Jacquard", occasion:"Reception" },
  { id:37, name:"Brocade Gold Sherwani", category:"sherwanis", gender:"men", price:42000, originalPrice:null, description:"Opulent brocade sherwani with rich gold weaving and antique button detailing.", sizes:["38","40","42","44"], colors:["Gold & Maroon","Gold & Navy"], stock:"low-stock", badge:"Premium", gradient:["#DAA520","#800020"], fabric:"Brocade", occasion:"Wedding" },
  { id:38, name:"Linen Festive Sherwani", category:"sherwanis", gender:"men", price:22500, originalPrice:28000, description:"Contemporary linen sherwani with subtle embroidery, ideal for day events.", sizes:["36","38","40","42","44","46"], colors:["Off-White","Sage Green","Dusty Pink"], stock:"in-stock", badge:"New", gradient:["#FAF0E6","#A8B5A0"], fabric:"Linen", occasion:"Festive" },
  { id:39, name:"Raw Silk Classic Sherwani", category:"sherwanis", gender:"men", price:35000, originalPrice:null, description:"Timeless raw silk sherwani with hand-cut dana and pearl embellishments.", sizes:["36","38","40","42","44"], colors:["Ivory","Peach","Light Gold"], stock:"in-stock", badge:"", gradient:["#FFFFF0","#EEE8AA"], fabric:"Raw Silk", occasion:"Wedding" },

  // ===== MEN'S KURTA PAJAMA =====
  { id:40, name:"Silk Pathani Kurta Set", category:"kurta-pajama", gender:"men", price:9999, originalPrice:null, description:"Classic Pathani-style silk kurta with matching pajama and pocket detailing.", sizes:["S","M","L","XL","XXL"], colors:["White","Cream","Black"], stock:"in-stock", badge:"", gradient:["#FFFFFF","#FFFDD0"], fabric:"Silk Blend", occasion:"Festive" },
  { id:41, name:"Cotton Lucknowi Kurta", category:"kurta-pajama", gender:"men", price:6500, originalPrice:8500, description:"Hand-embroidered Lucknowi chikankari kurta in fine cotton, a timeless classic.", sizes:["S","M","L","XL","XXL"], colors:["White","Light Blue","Mint"], stock:"in-stock", badge:"Bestseller", gradient:["#FFFFFF","#ADD8E6"], fabric:"Cotton", occasion:"Casual" },
  { id:42, name:"Designer Thread Kurta", category:"kurta-pajama", gender:"men", price:8200, originalPrice:null, description:"Contemporary kurta with contrast thread embroidery and mandarin collar.", sizes:["S","M","L","XL"], colors:["Navy","Olive","Maroon"], stock:"in-stock", badge:"New", gradient:["#000080","#556B2F"], fabric:"Cotton Silk", occasion:"Party" },
  { id:43, name:"Festive Brocade Kurta Set", category:"kurta-pajama", gender:"men", price:11500, originalPrice:15000, description:"Rich brocade kurta with woven patterns paired with silk churidar.", sizes:["S","M","L","XL","XXL"], colors:["Gold & Maroon","Silver & Navy"], stock:"in-stock", badge:"Festive", gradient:["#DAA520","#800020"], fabric:"Brocade", occasion:"Festive" },
  { id:44, name:"Printed Cotton Kurta Pajama", category:"kurta-pajama", gender:"men", price:4999, originalPrice:null, description:"Comfortable printed cotton kurta with relaxed fit, perfect for everyday wear.", sizes:["S","M","L","XL","XXL"], colors:["Blue Print","Green Print","Grey Print"], stock:"in-stock", badge:"", gradient:["#4169E1","#2E8B57"], fabric:"Cotton", occasion:"Casual" },
  { id:45, name:"Dupion Silk Kurta Set", category:"kurta-pajama", gender:"men", price:12800, originalPrice:null, description:"Premium dupion silk kurta with textured weave and gold-tipped buttons.", sizes:["S","M","L","XL"], colors:["Wine","Teal","Charcoal"], stock:"out-of-stock", badge:"", gradient:["#722F37","#008080"], fabric:"Dupion Silk", occasion:"Festive" },

  // ===== MEN'S SUITS & BANDHGALA =====
  { id:46, name:"Nehru Jacket with Kurta", category:"suits", gender:"men", price:14500, originalPrice:null, description:"Classic Nehru jacket in textured fabric paired with a silk kurta.", sizes:["S","M","L","XL","XXL"], colors:["Black & Gold","Navy & Silver","Maroon & Gold"], stock:"in-stock", badge:"Bestseller", gradient:["#1C1C1C","#DAA520"], fabric:"Jacquard & Silk", occasion:"Festive" },
  { id:47, name:"Silk Bandhgala Suit", category:"suits", gender:"men", price:28000, originalPrice:null, description:"Sleek Bandhgala suit in pure silk with structured shoulders and satin lapels.", sizes:["36","38","40","42","44"], colors:["Midnight Black","Deep Navy","Charcoal"], stock:"in-stock", badge:"Premium", gradient:["#0C0C0C","#191970"], fabric:"Pure Silk", occasion:"Formal" },
  { id:48, name:"Jodhpuri Suit Set", category:"suits", gender:"men", price:32500, originalPrice:38000, description:"Royal Jodhpuri suit with breeches-style trousers and ornate button work.", sizes:["36","38","40","42","44"], colors:["Ivory","Beige & Gold","Grey"], stock:"in-stock", badge:"Heritage", gradient:["#FFFFF0","#F5F5DC"], fabric:"Wool Blend", occasion:"Wedding" },
  { id:49, name:"Linen Blazer Kurta Set", category:"suits", gender:"men", price:18999, originalPrice:24000, description:"Modern linen blazer paired with cotton kurta and trousers. East meets West.", sizes:["S","M","L","XL","XXL"], colors:["Sand","Powder Blue","Sage"], stock:"low-stock", badge:"Trending", gradient:["#C2B280","#B0C4DE"], fabric:"Linen", occasion:"Party" },

  // ===== MEN'S INDO-WESTERN =====
  { id:50, name:"Asymmetric Kurta Jacket", category:"indo-western", gender:"men", price:16500, originalPrice:null, description:"Fashion-forward asymmetric kurta with attached draped jacket element.", sizes:["S","M","L","XL"], colors:["Black","Charcoal","Navy"], stock:"in-stock", badge:"Trending", gradient:["#1C1C1C","#36454F"], fabric:"Poly Silk", occasion:"Party" },
  { id:51, name:"Fusion Dhoti Sherwani", category:"indo-western", gender:"men", price:24000, originalPrice:null, description:"Contemporary dhoti-sherwani fusion with cowl drape and metallic buttons.", sizes:["S","M","L","XL"], colors:["Ivory & Gold","Black & Silver"], stock:"in-stock", badge:"New", gradient:["#FFFFF0","#1C1C1C"], fabric:"Silk Blend", occasion:"Wedding" },
  { id:52, name:"Modern Angrakha Set", category:"indo-western", gender:"men", price:13999, originalPrice:18000, description:"Revived Angrakha-style overlap kurta with contemporary tailoring and jogger pants.", sizes:["S","M","L","XL","XXL"], colors:["Rust","Olive","Steel Blue"], stock:"in-stock", badge:"Sale", gradient:["#B7410E","#556B2F"], fabric:"Cotton Silk", occasion:"Party" }
];

// Category metadata
const CATEGORIES = {
  women: [
    { id:"sarees", name:"Sarees", description:"Timeless drapes for every occasion", icon:"✦" },
    { id:"lehengas", name:"Lehengas", description:"Bridal & celebration ensembles", icon:"✦" },
    { id:"anarkalis", name:"Anarkalis", description:"Graceful floor-length elegance", icon:"✦" },
    { id:"gowns", name:"Gowns", description:"Indo-Western evening wear", icon:"✦" },
    { id:"kurta-sets", name:"Kurta Sets", description:"Everyday refined dressing", icon:"✦" }
  ],
  men: [
    { id:"sherwanis", name:"Sherwanis", description:"Regal wedding & occasion wear", icon:"✦" },
    { id:"kurta-pajama", name:"Kurta Pajama", description:"Classic comfort & style", icon:"✦" },
    { id:"suits", name:"Suits & Bandhgala", description:"Structured formal elegance", icon:"✦" },
    { id:"indo-western", name:"Indo-Western", description:"Modern fusion fashion", icon:"✦" }
  ]
};

// Helper functions
function getProductsByGender(gender) { return PRODUCTS.filter(p => p.gender === gender); }
function getProductsByCategory(category) { return PRODUCTS.filter(p => p.category === category); }
function getProductById(id) { return PRODUCTS.find(p => p.id === parseInt(id)); }
function getStockLabel(stock) { return stock === 'in-stock' ? 'In Stock' : stock === 'low-stock' ? 'Only Few Left' : 'Out of Stock'; }
function getStockClass(stock) { return stock === 'in-stock' ? 'stock-in' : stock === 'low-stock' ? 'stock-low' : 'stock-out'; }
function formatPrice(price) { return '₹' + price.toLocaleString('en-IN'); }
function searchProducts(query) {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p => p.name.toLowerCase().includes(q) || p.category.toLowerCase().includes(q) || p.fabric.toLowerCase().includes(q) || p.occasion.toLowerCase().includes(q) || p.description.toLowerCase().includes(q));
}
